In [1]:
import numpy as np

In [2]:
l = [1,2,3,4]

In [4]:
ar = np.array(l)

In [5]:
type(ar)

numpy.ndarray

In [6]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [7]:
np.asarray(l)

array([1, 2, 3, 4])

In [8]:
a = [2,3,4]

In [9]:
np.asanyarray(a)

array([2, 3, 4])

In [10]:
c = a
#shallow copy

In [11]:
c

[2, 3, 4]

In [12]:
a

[2, 3, 4]

In [13]:
c[0] = 100

In [14]:
a

[100, 3, 4]

In [15]:
d = np.copy(a)
#deep copy

In [16]:
d

array([100,   3,   4])

In [17]:
a

[100, 3, 4]

In [18]:
d[1] = 400

In [19]:
d

array([100, 400,   4])

In [20]:
a

[100, 3, 4]

In [21]:
np.fromfunction(lambda i,j : i == j, (3,3))
#it will check in 3*3 matrix row nd column 123

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [22]:
iterable = (i*i for i in range(5))

In [23]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [24]:
np.fromstring('234 234', sep=' ')
#it will separate string and store into array where space is happen 

array([234., 234.])

In [25]:
np.fromstring('4,5', sep=',')
#here we pass that where , is found separate the string

array([4., 5.])

In [26]:
#Numpy - Data  Types

In [27]:
l = [2,3,4,5,6]

In [28]:
ar = np.array(l)

In [29]:
ar

array([2, 3, 4, 5, 6])

In [30]:
ar.ndim
#what dimensional it will find

1

In [31]:
ar2 = np.array([[1,2,3,4], [2,3,4,5]])

In [32]:
ar2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [33]:
ar2.ndim

2

In [34]:
ar.size

5

In [35]:
ar2.size

8

In [36]:
ar.shape

(5,)

In [37]:
ar2.shape
# 2 row 4 column

(2, 4)

In [39]:
ar2.dtype

dtype('int64')

In [40]:
ar22 = np.array([(1.4,45,45),(23,45,66)])

In [42]:
ar22
#here we use floting no so it will convert all into floating no 

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [43]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [44]:
np.arange(2.3,5.6,.3)

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [45]:
list(np.arange(2.3,5.6,.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [46]:
np.linspace(1,5,10)
#it will produce 10 data from 1 to 5 , with 10 space 

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [47]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [48]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [50]:
np.zeros((3,4,2))
#3 matrix of 4*2 matrix

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [51]:
np.ones(4)

array([1., 1., 1., 1.])

In [53]:
on = np.ones((2,3,2))

In [54]:
on + 5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [56]:
np.empty((3,6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [58]:
np.eye(4)
#identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [60]:
np.linspace(2,4,20)
#20 data 

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [61]:
np.logspace(2,5,10,base = 2)
#base 2 it will find all the log value 

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [64]:
arr = np.random.randn(3,4)
#random data

In [65]:
import pandas as pd

In [66]:
pd.DataFrame(arr)
#here we convert into dataframe of the rando data 

0         1         2         3
0  1.716132 -0.505669  0.784023  0.107941
1 -0.301864  0.514842 -1.303178  1.456898
2 -0.720966  1.305615  1.589968 -2.530557

In [67]:
arr
#arr data is in dataframe

array([[ 1.716132  , -0.50566908,  0.78402276,  0.10794136],
       [-0.30186392,  0.51484156, -1.30317844,  1.45689775],
       [-0.72096641,  1.30561494,  1.58996785, -2.53055691]])

In [68]:
np.random.rand(3,4)

array([[0.42501092, 0.67146894, 0.95469319, 0.45516078],
       [0.06277201, 0.74922264, 0.68488843, 0.64939223],
       [0.32758371, 0.7684857 , 0.60617633, 0.21455951]])

In [72]:
pd.DataFrame(np.random.randint(1,110,(300,400))).to_csv('testmy.csv')
# 3 row 4 colume 
# now it will converted into csv file 

In [73]:
arr = np.random.rand(3,4)

In [74]:
arr

array([[0.29662071, 0.01915379, 0.19034153, 0.56651668],
       [0.83471228, 0.16461081, 0.46109652, 0.60930119],
       [0.36483883, 0.85044998, 0.58624269, 0.82486889]])

In [76]:
arr1 = arr.reshape(6,2)

In [77]:
arr1

array([[0.29662071, 0.01915379],
       [0.19034153, 0.56651668],
       [0.83471228, 0.16461081],
       [0.46109652, 0.60930119],
       [0.36483883, 0.85044998],
       [0.58624269, 0.82486889]])

In [79]:
arr1[1,1]
#find the 1,1 data

0.5665166757861698

In [80]:
arr1[2:5]

array([[0.83471228, 0.16461081],
       [0.46109652, 0.60930119],
       [0.36483883, 0.85044998]])

In [82]:
arr1[2:5,1]
#1 dimension 

array([0.16461081, 0.60930119, 0.85044998])

In [83]:
arr = np.random.randint(1,100,(5,5))

In [84]:
arr

array([[95, 11, 35, 95, 13],
       [70,  6, 69, 98, 86],
       [77, 59, 53, 10, 32],
       [25, 56,  9,  3, 73],
       [53, 29, 59, 76, 94]])

In [85]:
arr[arr>50]

array([95, 95, 70, 69, 98, 86, 77, 59, 53, 56, 73, 53, 59, 76, 94])

In [86]:
arr[2:4, [1,2]]
#1&2 column

array([[59, 53],
       [56,  9]])

In [87]:
arr[0][0] = 5000

In [88]:
arr

array([[5000,   11,   35,   95,   13],
       [  70,    6,   69,   98,   86],
       [  77,   59,   53,   10,   32],
       [  25,   56,    9,    3,   73],
       [  53,   29,   59,   76,   94]])

In [89]:
arr1 = np.random.randint(1,3, (3,3))
arr2 = np.random.randint(1,3, (3,3))


In [90]:
arr1+arr2

array([[2, 3, 4],
       [2, 4, 3],
       [3, 3, 3]])

In [91]:
arr1*arr2

array([[1, 2, 4],
       [1, 4, 2],
       [2, 2, 2]])

In [92]:
arr1

array([[1, 2, 2],
       [1, 2, 1],
       [2, 2, 1]])

In [93]:
arr2

array([[1, 1, 2],
       [1, 2, 2],
       [1, 1, 2]])

In [95]:
arr1@arr2
#@use matrix multiplication , * only index multiplication

array([[ 5,  7, 10],
       [ 4,  6,  8],
       [ 5,  7, 10]])

In [96]:
arr1 + 100

array([[101, 102, 102],
       [101, 102, 101],
       [102, 102, 101]])

In [97]:
arr1**2

array([[1, 4, 4],
       [1, 4, 1],
       [4, 4, 1]])

In [98]:
#numpy - Brodcast


In [100]:
arr = np.zeros((4,4))

In [101]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [102]:
row = np.array([1,2,3,4])

In [103]:
row

array([1, 2, 3, 4])

In [104]:
arr + row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [105]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [106]:
row.T

array([1, 2, 3, 4])

In [107]:
col = np.array([[1,2,3,4]])

In [108]:
col.T
#transpose

array([[1],
       [2],
       [3],
       [4]])

In [109]:
col.T + arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [110]:
arr1 = np.random.randint(1,4, (3,4))

array([[2, 1, 1, 3],
       [2, 1, 1, 1],
       [2, 3, 1, 3]])

In [111]:
arr1

array([[1, 2, 2],
       [1, 2, 1],
       [2, 2, 1]])

In [112]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.41421356],
       [1.        , 1.41421356, 1.        ],
       [1.41421356, 1.41421356, 1.        ]])

In [114]:
np.exp(arr1)

array([[2.71828183, 7.3890561 , 7.3890561 ],
       [2.71828183, 7.3890561 , 2.71828183],
       [7.3890561 , 7.3890561 , 2.71828183]])

In [115]:
np.log10(arr1)

array([[0.     , 0.30103, 0.30103],
       [0.     , 0.30103, 0.     ],
       [0.30103, 0.30103, 0.     ]])

In [116]:
#numpy part 1 end

In [117]:
#Numpy - Array Manipulation 

In [118]:
import numpy as np

In [119]:
arr = np.random.randint(1,10,(3,4))

In [120]:
arr

array([[7, 2, 5, 6],
       [3, 1, 4, 3],
       [5, 2, 9, 3]])

In [121]:
arr.reshape(2,6)

array([[7, 2, 5, 6, 3, 1],
       [4, 3, 5, 2, 9, 3]])

In [122]:
arr.T

array([[7, 3, 5],
       [2, 1, 2],
       [5, 4, 9],
       [6, 3, 3]])

In [124]:
arr.flatten()

array([7, 2, 5, 6, 3, 1, 4, 3, 5, 2, 9, 3])

In [125]:
arr1 = np.array([1,2,3,4,5])

In [127]:
arr1.ndim

1

In [128]:
np.expand_dims(arr1, axis=1)
#change dimension 

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [129]:
np.expand_dims(arr1, axis=0)

array([[1, 2, 3, 4, 5]])

In [130]:
arr

array([[7, 2, 5, 6],
       [3, 1, 4, 3],
       [5, 2, 9, 3]])

In [131]:
np.squeeze(arr)

array([[7, 2, 5, 6],
       [3, 1, 4, 3],
       [5, 2, 9, 3]])

In [132]:
data = np.array([[1],[2],[3]])

In [133]:
data

array([[1],
       [2],
       [3]])

In [134]:
np.squeeze(data)

array([1, 2, 3])

In [135]:
arr1

array([1, 2, 3, 4, 5])

In [136]:
np.repeat(arr1,3)
#repeat 3 times

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5])

In [138]:
np.roll(arr1,2)
#roll the data by 2 place

array([4, 5, 1, 2, 3])

In [139]:
arr1

array([1, 2, 3, 4, 5])

In [140]:
np.roll(arr1,3)


array([3, 4, 5, 1, 2])

In [141]:
arr1

array([1, 2, 3, 4, 5])

In [142]:
np.diag(arr1)
#all data in diagonal and creates matrix 

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [143]:
#numpy - Binary operation

In [144]:
arr1 = np.random.randint(1,10,(3,4))

In [145]:
arr2 = np.random.randint(1,10,(3,4))

In [146]:
arr1

array([[8, 1, 9, 9],
       [1, 4, 2, 6],
       [1, 6, 2, 9]])

In [147]:
arr2

array([[3, 2, 8, 5],
       [5, 6, 1, 1],
       [8, 1, 7, 9]])

In [148]:
arr1+arr2

array([[11,  3, 17, 14],
       [ 6, 10,  3,  7],
       [ 9,  7,  9, 18]])

In [149]:
arr1*arr2

array([[24,  2, 72, 45],
       [ 5, 24,  2,  6],
       [ 8,  6, 14, 81]])

In [150]:
arr1/arr2

array([[2.66666667, 0.5       , 1.125     , 1.8       ],
       [0.2       , 0.66666667, 2.        , 6.        ],
       [0.125     , 6.        , 0.28571429, 1.        ]])

In [151]:
arr1-arr2

array([[ 5, -1,  1,  4],
       [-4, -2,  1,  5],
       [-7,  5, -5,  0]])

In [152]:
arr1%arr2

array([[2, 1, 1, 4],
       [1, 4, 0, 0],
       [1, 0, 2, 0]])

In [153]:
arr1 ** arr2

array([[      512,         1,  43046721,     59049],
       [        1,      4096,         2,         6],
       [        1,         6,       128, 387420489]])

In [154]:
arr1 & arr2

array([[0, 0, 8, 1],
       [1, 4, 0, 0],
       [0, 0, 2, 9]])

In [155]:
arr1

array([[8, 1, 9, 9],
       [1, 4, 2, 6],
       [1, 6, 2, 9]])

In [156]:
arr2

array([[3, 2, 8, 5],
       [5, 6, 1, 1],
       [8, 1, 7, 9]])

In [157]:
~arr1

array([[ -9,  -2, -10, -10],
       [ -2,  -5,  -3,  -7],
       [ -2,  -7,  -3, -10]])

In [158]:
arr1|arr2

array([[11,  3,  9, 13],
       [ 5,  6,  3,  7],
       [ 9,  7,  7,  9]])

In [159]:
arr1>arr2

array([[ True, False,  True,  True],
       [False, False,  True,  True],
       [False,  True, False, False]])

In [160]:
#numpy string function

In [162]:
arr = np.array(['sudh','kumar'])

In [163]:
arr

array(['sudh', 'kumar'], dtype='<U5')

In [164]:
np.char.upper(arr)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [165]:
np.char.title(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [166]:
np.char.capitalize(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [167]:
#numpy Mathematical function

In [168]:
arr1

array([[8, 1, 9, 9],
       [1, 4, 2, 6],
       [1, 6, 2, 9]])

In [169]:
np.sin(arr1)

array([[ 0.98935825,  0.84147098,  0.41211849,  0.41211849],
       [ 0.84147098, -0.7568025 ,  0.90929743, -0.2794155 ],
       [ 0.84147098, -0.2794155 ,  0.90929743,  0.41211849]])

In [170]:
np.cos(arr1)

array([[-0.14550003,  0.54030231, -0.91113026, -0.91113026],
       [ 0.54030231, -0.65364362, -0.41614684,  0.96017029],
       [ 0.54030231,  0.96017029, -0.41614684, -0.91113026]])

In [171]:
np.tan(arr1)

array([[-6.79971146,  1.55740772, -0.45231566, -0.45231566],
       [ 1.55740772,  1.15782128, -2.18503986, -0.29100619],
       [ 1.55740772, -0.29100619, -2.18503986, -0.45231566]])

In [172]:
np.tanh(arr1)

array([[0.99999977, 0.76159416, 0.99999997, 0.99999997],
       [0.76159416, 0.9993293 , 0.96402758, 0.99998771],
       [0.76159416, 0.99998771, 0.96402758, 0.99999997]])

In [173]:
np.log10(arr1)

array([[0.90308999, 0.        , 0.95424251, 0.95424251],
       [0.        , 0.60205999, 0.30103   , 0.77815125],
       [0.        , 0.77815125, 0.30103   , 0.95424251]])

In [174]:
np.exp(arr1)

array([[2.98095799e+03, 2.71828183e+00, 8.10308393e+03, 8.10308393e+03],
       [2.71828183e+00, 5.45981500e+01, 7.38905610e+00, 4.03428793e+02],
       [2.71828183e+00, 4.03428793e+02, 7.38905610e+00, 8.10308393e+03]])

In [175]:
np.sqrt(arr1)

array([[2.82842712, 1.        , 3.        , 3.        ],
       [1.        , 2.        , 1.41421356, 2.44948974],
       [1.        , 2.44948974, 1.41421356, 3.        ]])

In [176]:
np.power(arr1,2)

array([[64,  1, 81, 81],
       [ 1, 16,  4, 36],
       [ 1, 36,  4, 81]])

In [177]:
arr1

array([[8, 1, 9, 9],
       [1, 4, 2, 6],
       [1, 6, 2, 9]])

In [178]:
np.mean(arr1)

4.833333333333333

In [179]:
np.median(arr1)

5.0

In [180]:
np.std(arr1)

3.2360813064912666

In [181]:
np.var(arr1)

10.472222222222223

In [182]:
np.min(arr1)

1

In [183]:
np.max(arr1)

9

In [184]:
#numpy part 3 

In [185]:
#sorting searching and counting functions

In [186]:
arr = np.array([4,3,4,5,6,7,455,7,78,66])

In [187]:
arr

array([  4,   3,   4,   5,   6,   7, 455,   7,  78,  66])

In [188]:
np.sort(arr)

array([  3,   4,   4,   5,   6,   7,   7,  66,  78, 455])

In [189]:
np.searchsorted(arr,34)
#where we insert that place it will say

8

In [190]:
arr1 = np.array([0,3,4,44,423,0,0,0,0])

In [191]:
#finding non zero
np.count_nonzero(arr1)

4

In [192]:
arr

array([  4,   3,   4,   5,   6,   7, 455,   7,  78,  66])

In [193]:
np.where(arr > 6)

(array([5, 6, 7, 8, 9]),)

In [195]:
np.extract(arr>6,arr)

array([  7, 455,   7,  78,  66])

In [196]:
#numpy byte swapping
arr.byteswap()

array([  288230376151711744,   216172782113783808,   288230376151711744,
         360287970189639680,   432345564227567616,   504403158265495552,
       -4107001385185181696,   504403158265495552,  5620492334958379008,
        4755801206503243776])

In [197]:
#numpy -copies and views 
arr

array([  4,   3,   4,   5,   6,   7, 455,   7,  78,  66])

In [198]:
a = np.copy(arr)

In [199]:
b = arr.view()
#view is equal to shallow copy

In [200]:
b

array([  4,   3,   4,   5,   6,   7, 455,   7,  78,  66])

In [201]:
arr

array([  4,   3,   4,   5,   6,   7, 455,   7,  78,  66])

In [205]:
b[0] = 67

In [206]:
b

array([ 67,   3,   4,   5,   6,   7, 455,   7,  78,  66])

In [207]:
arr

array([ 67,   3,   4,   5,   6,   7, 455,   7,  78,  66])

In [208]:
#numpy -matrix liabray 
import numpy.matlib as nm

In [209]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [213]:
nm.ones((3,4))


matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [214]:
nm.eye(5)
#identity matrix

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [215]:
#numpy -linear algebra 


In [216]:
arr1 = np.random.randint([[2,3],[4,5]])

In [217]:
arr2 = np.random.randint([[5,3],[2,5]])

In [218]:
np.dot(arr1,arr2)

array([[0, 2],
       [0, 6]])

In [219]:
arr1@arr2

array([[0, 2],
       [0, 6]])

In [220]:
#Numpy end